apiVersion: v1
kind: Pod
metadata:
  name: log-app
  labels:
    app: log-app
spec:
  containers:
    - name: log-app
      image: quay.io/leahnp/leah_log_app:latest
      ports:
      - containerPort: 8080